### PR TITLE
Run call_periodically callbacks in executor

### PR DESCRIPTION
**Pull request by roganov**
`check_all` function is a blocking one and takes considerable amount of time to execute on big projects.
Besides from event loop blockage, asyncio generates lots of following warnings:
```
Executing <Handle <TaskWakeupMethWrapper object at 0x7f3449270738> created at /usr/lib64/python3.6/asyncio/futures.py:343> took 0.140 seconds
```

### CODE REVIEW

**Comment by and800** [comment]
Thanks!

This problem definitely needs to be fixed. Bu I'm quite afraid to fire process management syscalls like `exec()` inside an executor. Although default executor should be threaded and restart in thread will affect whole process, there can be some issues.
1. custom loops may provide custom executors
2. it is simply a bad practice to do this outside main thread, I think

I am currently thinking about alternative approaches. What if we somehow make `check_all()` non-blocking? It is iterating over large list of files. I think we can split those files into chunks, and after processing each chunk we return control to the loop

**Comment by roganov** [comment]
`check_all` cannot possible be made non-blocking since it makes `os.stat` calls.

I propose the following:
- extract files checks from `check_all` to a new function which will return `True` if reload is needed
- `check_all` will call the new function in a custom `ThreadPoolExecutor(1)` executor and call `reload()` if needed

This way all `os.stat` calls will be made in a worker thread and the process will be reloaded from the main thread.

**Comment by and800** [comment]
something like this: 5b929620701088a4459c43dbd9770e3c93147199
I will double check this and then release

**Comment by roganov** [comment]
This will not work if default executor is process based because `sys.modules` will be different.

```
import sys
from asyncio import get_event_loop
from concurrent.futures import ProcessPoolExecutor


loop = get_event_loop()
loop.set_default_executor(ProcessPoolExecutor(1))


def modules_list():
    return list(sys.modules)


async def test():
    print(set(sys.modules).symmetric_difference(set(await loop.run_in_executor(None, modules_list))))
    import decimal
    print(set(sys.modules).symmetric_difference(set(await loop.run_in_executor(None, modules_list))))


loop.run_until_complete(test())
```

**Comment by roganov** [comment]
I've updated the PR to run check_all in special executor.

**Comment by and800** [comment]
Released as v0.2.0
Thank you!

**Pull request merged**
